version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    branches:
      only:
        - development
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  test:
    steps:
      - run: npm test
workflows:
    build-and-test:
      jobs:
        - build
        - test