version: 2
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  test:
    steps:
      - run: npm test
workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only: development
      - test:
          filters:
              branches:
                only: development
        
