version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: npm install
workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only: development
